version: "3"

services:
  air_freight_server:
    container_name: air_freight_server
    image: nginx:1.23
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8000:80"
    restart: always

  air_freight_app:
    container_name: air_freight_app
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
      - ./_docker/app/php.ini:/usr/local/etc/php/php.ini
      - ./_docker/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - air_freight_server
      - air_freight_database

  air_freight_database:
    container_name: air_freight_database
    env_file:
      - .env
    ports:
      - "8001:${DB_PORT}"
    image: postgres:15.0
    volumes:
      - ./_docker/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always

  air_freight_adminer:
    container_name: air_freight_adminer
    image: adminer
    depends_on:
      - air_freight_database
    restart: always
    ports:
      - "8002:8080"
